### ISSUE TITLE
Temperature and Humidity Sensor Interface

### ISSUE THREAD

**Issue by mikeshams** [Group-1-winter-2021/ESE4009_2#2]
Ratna - Review these two links and put your comments before end of class today!
1. https://www.youtube.com/watch?v=reYa_4rh0-w&feature=youtu.be
2. https://docs.python.org/3/extending/embedding.html?highlight=pfunc#very-high-level-embedding

**Comment by capstonepro** [comment]
In the first video its a detailed manual explanation about the DHT11 sensor about its data transmission , working of DHT 11 SENSOR,  how it communicates with microcontroller and brief explanation differences between module and sensor. The second link is about the conversion of data values from python to c . To give commands how to use them in python code.

**Comment by mikeshams** [comment]
Use the second link to integrate your python code into C by Monday March 8.

**Comment by capstonepro** [comment]
#include <stdio.h>
#include<stdlib.h>
#include<Python.h>
int main()
{
char filename[ ]="simpletest.py";
FILE* fp;
Py_Initialize();
fp=_py_fopen(simpletest.py,"r");
Py Run_simplefile(fp,simpletest.py);
Py_finalize();
return 0; 
First we need to initialize the python environment and then clean. Then include the header files for declaration to code files. 
Declare a file to store the program or integrated C file. Initialize the python code. In next step we have opened the "simpletest.py" in the read mode. Get the code using the command Py_Run_simplefile which helps in allocating memory space and loading file content . last the Py_finalize ends the program.  The file we are using in this is "Simpletest.py".

**Comment by capstonepro** [comment]
The second which we tried to work out is :
#include<stdio.h>
#include<stdlib.h>
int main()
{
system("python simpletest.py");
return 0;
}
The working of this file is similar to the previous and we include the header files and include the int main to return integer type data. Then the real function system as its a standard library and use to pass the command that can be in command processor or the terminal .
