### ISSUE TITLE
UV Sensor Interface

### ISSUE THREAD

**Issue by mikeshams** [Group-1-winter-2021/ESE4009_2#4]
Prabnoor - What issues did you face? How to resolve?

**Comment by noor302972** [comment]
First we have to detect the i2c devices connected to beaglebone so for that we need to find the commands for enabling i2c ports.
First we have to type sudo config pin9.17 i2c 
sudo config pin9.18 i2c
Then after typing command i2c detect -r 1 it will show In which address sensor is connected. After that we clone the repository then we have to compile the files using make command and execute the file to get the output. 
used the link --https://github.com/jordan336/si1145
