### ISSUE TITLE
PCB Implementation

### ISSUE THREAD

**Issue by mikeshams** [Group-1-winter-2021/ESE4009_2#5]
Ratna - what issues did you face and how you resolved them?

**Comment by capstonepro** [comment]
i faced an issue putting the header pin as one of my classmate had but forcing them on both ways i could connect all parts. The soldering iron use to get heated a lot and while soldering its very tough to see the pours are filler by solder. we use to on the torch and use camera to see clear view and switch off the solder iron for few minutes and on to be safe.
