### ISSUE TITLE
PCB designing

### ISSUE THREAD

**Issue by mikeshams** [Group-1-winter-2021/ESE4009_2#6]
Prabnoor - What made the PCB fabricating company could not create the conducting tracks for you? How can you correct the gerber file? Demonstrate it in class!

**Comment by noor302972** [comment]
When i created the pcb design i thought it already comes with a copper area but later i found that we need to create it ourselves and the option is available in PCB tools. We just need to select the layer ie top,bottom where we want to create the copper area and than we can create the gerber file.
