### ISSUE TITLE
Plug & Play Mode

### ISSUE THREAD

**Issue by mikeshams** [Group-1-winter-2021/ESE4009_2#7]
How did you make your project in plug and play mode? Explain about the steps you have taken here!

**Comment by capstonepro** [comment]
To make the project in plug and play mode, these are the steps involved in it
1. After successfully executing the project prototype we need to create the executable file of our final code that we want to run while booting up the system.
2. After creating the executable file , we can make use of the systemd service 
3. Then we need to create  file in .service mode in the path  : /lib/systemd/system/autostart.service , here the autostart.service is the file we are creating.
4. Then when open the file we need to edit the script with the executable file we created in step1, make sure to give the exact path of that file
5. then save the file after creating the script
6. then we can try running the script while booting the beaglebone

Here is the link that i used as a reference for this task
http://beaglebone.cameon.net/home/autostarting-services

**Comment by mikeshams** [comment]
But how did you integrate different codes you needed for different tasks?

**Comment by capstonepro** [comment]
As we have the codes for interfacing different tasks for all the components individually for the beaglebone and arduino as well , we need to write a main program which should include all the libraries and header files that are there for the individual tasks,then created a main function and used the code that has for individual tasks and also used some other loop functions for conditions to run the code properly .
Then for the arduino ide also created a new code and integrated all the previous tasks code that have been successfully compiled and then made use of some condition like if(), while() and some variables and integrated the whole code according to the project requirement
